#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin $Script);
use Fcntl qw(:flock SEEK_END);
use POSIX;

use lib $Bin;
use Cammy;

my ($dir) = @ARGV;
die "Syntax: $Script <dir>" unless $dir and -d $dir;

retire($dir);
